/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import ModelClass.Usuario;
import Models.Cajas;
import Models.Usuarios;
import java.awt.Color;
import java.util.List;

/**
 *
 * @author AlexJPZ
 */
public class Login extends javax.swing.JFrame {

    Usuario usuario = new Usuario();

    public Login() {

        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        Label_Mensaje.setText("");
        TextField_Usuario.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Label_Usuario = new javax.swing.JLabel();
        TextField_Usuario = new javax.swing.JTextField();
        Label_Pass = new javax.swing.JLabel();
        PasswordField_Pass = new javax.swing.JPasswordField();
        Label_Mensaje = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(34, 45, 65));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Usuario.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Label_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Label_Usuario.setText("Usuario");
        jPanel2.add(Label_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        TextField_Usuario.setBackground(new java.awt.Color(34, 45, 65));
        TextField_Usuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TextField_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        TextField_Usuario.setBorder(null);
        TextField_Usuario.setCaretColor(new java.awt.Color(255, 255, 255));
        TextField_Usuario.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        TextField_Usuario.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        TextField_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_UsuarioKeyReleased(evt);
            }
        });
        jPanel2.add(TextField_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 250, 35));

        Label_Pass.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Label_Pass.setForeground(new java.awt.Color(255, 255, 255));
        Label_Pass.setText("Contraseña");
        jPanel2.add(Label_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        PasswordField_Pass.setBackground(new java.awt.Color(34, 45, 65));
        PasswordField_Pass.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PasswordField_Pass.setForeground(new java.awt.Color(255, 255, 255));
        PasswordField_Pass.setBorder(null);
        PasswordField_Pass.setCaretColor(new java.awt.Color(255, 255, 255));
        PasswordField_Pass.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        PasswordField_Pass.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        PasswordField_Pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PasswordField_PassKeyReleased(evt);
            }
        });
        jPanel2.add(PasswordField_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 250, 33));

        Label_Mensaje.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Label_Mensaje.setForeground(new java.awt.Color(255, 51, 102));
        Label_Mensaje.setText("Mensaje");
        jPanel2.add(Label_Mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jButton1.setBackground(new java.awt.Color(95, 210, 195));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Iniciar Sesión");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 250, 50));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 250, 12));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 250, 12));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inicio de Sesión");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 320, 550));

        jPanel3.setBackground(new java.awt.Color(95, 210, 195));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("©Papelería Manantial");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/libro 4.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_UsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_UsuarioKeyReleased
        if (TextField_Usuario.getText().equals("")) {
            Label_Usuario.setForeground(new Color(102, 102, 102));
        } else {
            Label_Usuario.setText("Usuario");
            Label_Usuario.setForeground(new Color(0, 153, 51));
        }
        Label_Mensaje.setText("");
    }//GEN-LAST:event_TextField_UsuarioKeyReleased

    private void PasswordField_PassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordField_PassKeyReleased
        String pass = new String(PasswordField_Pass.getPassword());
        if (pass.equals("")) {
            Label_Pass.setForeground(new Color(102, 102, 102));
        } else {
            Label_Pass.setText("Contraseña");
            Label_Pass.setForeground(new Color(0, 153, 51));
        }
        Label_Mensaje.setText("");
    }//GEN-LAST:event_PasswordField_PassKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        iniciarSesion();
    }//GEN-LAST:event_jButton1ActionPerformed
    private void iniciarSesion() {
        if (TextField_Usuario.getText().equals("")) {
            Label_Usuario.setText("Ingrese el usuario");
            Label_Usuario.setForeground(Color.RED);
            TextField_Usuario.requestFocus();
        } else {
            String pass = new String(PasswordField_Pass.getPassword());
            if (pass.equals("")) {
                Label_Pass.setText("Ingrese la contraseña");
                Label_Pass.setForeground(Color.RED);
                PasswordField_Pass.requestFocus();
            } else {
                Object[] objects = usuario.login(TextField_Usuario.getText(), pass);
                List<Usuarios> listUsuario = (List<Usuarios>) objects[0];
                List<Cajas> listCaja = (List<Cajas>) objects[1];
                if (0 < listUsuario.size()) {
                    if (listUsuario.get(0).getRole().equals("Admin")) {
                        Sistema sisten = new Sistema(listUsuario, listCaja);
                        sisten.setVisible(true);
                        sisten.setExtendedState(MAXIMIZED_BOTH);
                        this.setVisible(false);
                    } else {
                        if (0 < listCaja.size()) {
                            Sistema sisten = new Sistema(listUsuario, listCaja);
                            sisten.setVisible(true);
                            sisten.setExtendedState(MAXIMIZED_BOTH);
                            this.setVisible(false);
                        } else {
                            Label_Mensaje.setText("No hay cajas disponibles");
                        }
                    }
                } else {
                    Label_Mensaje.setText("Usuario o Contraseña incorrecta");
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Mensaje;
    private javax.swing.JLabel Label_Pass;
    private javax.swing.JLabel Label_Usuario;
    private javax.swing.JPasswordField PasswordField_Pass;
    private javax.swing.JTextField TextField_Usuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

}
